### ISSUE TITLE
Value Error when running preprocess

### ISSUE THREAD

**Issue by pfrcks** [harvardnlp/sent-conv-torch#14]
Hi, I'm currently facing the following issue with the given code.

```
[pfrcks:...jects/CBDet/sent-conv-torch]$ python preprocess.py MR ~/Downloads/GoogleNews-vectors-negative300.bin.gz
Traceback (most recent call last):
  File "preprocess.py", line 224, in <module>
    main()
  File "preprocess.py", line 195, in main
    w2v = load_bin_vec(args.w2v, word_to_idx)
  File "preprocess.py", line 15, in load_bin_vec
    vocab_size, layer1_size = map(int, header.split())
ValueError: invalid literal for int() with base 10: '\x1f\x8b\x08\x08\x80\xff\xa8R\x02\x03GoogleNews-vectors-negative300.bin'
```

Can you please shed some light on this? I've also tried using the word2vec taken from https://code.google.com/archive/p/word2vec/ source but it gives the same error.

**Comment by jeffreyling** [comment]
You need to ungzip the file so that it's a .bin.
